### ISSUE TITLE
Global Macro for random speech

### ISSUE THREAD

**Issue by aureliosaraiva** [CCOSTAN/Home-AssistantConfig#1018]
Hi Carlo, how are you?

I use your idea of creating more sound integrations a lot, making each one interact more proactively with people.

I've been following your idea for a while, added a set of random phrases in the automations.

But I started to get lost whenever I need the phrases better or even correct, because it is spread in several files.

So create a custom component that creates a helper for jinja2 to return a random phrase.

The custom component is simple, but it allows me to greatly simplify the management of these scattered phrases.

```yaml
global_macro:
  speech: 
     welcome:
        - phrases 1
        - phrases 2
     sleep_mode:
        - other phrases 1
        - other phrases 2
```

```yaml
- service: script.speech_engine
      data_template:
        custom_message: >
          {{random_speech('welcome')}}
        call_no_random: 1
```

https://github.com/aureliosaraiva/HomeAssistant-config/blob/main/config/custom_components/global_macro/__init__.py

https://github.com/aureliosaraiva/HomeAssistant-config/blob/main/config/configuration.yaml#L32

https://github.com/aureliosaraiva/HomeAssistant-config/blob/main/config/speech.yaml

Well, that's it. I'm just sharing something with someone who always teaches us too.

Thanks
