### ISSUE TITLE
Webcal.fi no longer works - Breaks Flag Sensor

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#1141]
https://github.com/uherting/MyHA-Configuration/issues/1

https://github.com/Backslashh/homeassistant-config/issues/18

**Comment by CCOSTAN** [comment]
Should be able to leverage WolfRAM TO DETERMINE IF IT'S FLAG DAY OR NOT. 

```yaml
wolframalpha_flagday_api: https://api.wolframalpha.com/v2/result?appid=JIUY8U-4V8KY45VT1&i=IS%20TODAY%20FLAG%20DAY

  - platform: rest
    name: Halloween Countdown
    resource: !secret wolframalpha_flagday_api
#    value_template: "{{ (value|replace(' days', '')) | int }}"
 #   unit_of_measurement: Days
    scan_interval: 43200

```
