### ISSUE TITLE
Leverage new Wait template. 

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#224]
```yaml
script:
  tts_wait_test:
    sequence:
      - service: script.say
        data:
          message: "Hello World. I am Google Home, your personal assistant. I had to make this a little longer just to be able to test it properly."

      - wait_template: >-
          {{ is_state('media_player.dining_room_home', 'playing') }}
        timeout: '00:00:05'

      - wait_template: >-
          {{ not is_state('media_player.dining_room_home', 'playing') }}
        timeout: '00:01:00'

      - service: script.say
        data:
          message: "I waited until I finished saying the previous statement, so that I can say this one."

```
