### ISSUE TITLE
Wake on LAN

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#24]
#Wake on Lan stuff to try 
 ```yaml 
- platform: wake_on_lan
  mac_address: XX:XX:XX:XX:XX:XX
  name: "Synology WOL"
  host: "192.168.1.3"

- platform: wake_on_lan
  mac_address: XX:XX:XX:XX:XX:XX
  name: "iMac WOL"
  host: "192.168.1.2"
```
