### ISSUE TITLE
Blinking for Floorplan

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#241]
This should do the trick:

floorplan.css:
```css
.blinking {
  animation: blink 2s linear infinite;
}

@keyframes blink {  
  50% { opacity: 0; }
}
```
Make sure to add class: blinking to your entity ID in your floorplan.yaml

You can change the speed of the blink by changing the animation time (I just used 2s as a starting point)
