### ISSUE TITLE
Using the rest sensor to create more sensors. 

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#274]
```yaml

sensor:
  - platform: rest
    # resource: https://launchlibrary.net/1.2.2/launch/next/10
    resource: https://raw.githubusercontent.com/cribbstechnologies/ha_config/master/www/test_launch.json
    name: launch window
    # if the current timestamp is in the launch window
    # this sensor will return the UTC timestamp of the launch
    sensors:
      sensor_1:
        json_path: 'launches[0].name'
        value_template: 'True'
      sensor_2:
        json_path: 'launches[0].vidURLs[0]'
        value_template: 'False'
```

CC: @cribbstechnologies
