### ISSUE TITLE
HUGE Move to the laptop.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#292]
**Installed Ubuntu on the laptop**
**Updated WiFi - uses NETPLAN**
**Disabled Power Management** - https://askubuntu.com/a/594417/777093
**Edited the SUDOERS file.**
**Installed DOCKER** - https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/
**Installed Cockpit management
Installed tuned - server-powersaving**

Containers:
Dasher - https://hub.docker.com/r/clemenstyp/dasher-docker/
Home Assistant
MQTT - eclipse-mosquitto:latest
HomeBridge - oznu/homebridge:latest

![image](https://user-images.githubusercontent.com/2160436/34472099-907e616c-ef27-11e7-979b-b81b0655c3e6.png)

#290 really helped make this happen.

**Comment by brent20** [comment]
Just curious - why the move to Ubuntu and a Laptop? I did finally make the switch from the Pi3 to an Ubuntu VM on ESXi and it's fantastic. Also that broadlink should serve you well, one of the best investments for Home Assistant, works great with ceiling fans that only have 1 circuit for light/fan.

**Comment by CCOSTAN** [comment]
@brent20  I happen to have a pretty fast Laptop just sitting here.  That's the big reason to move to it instead of purchasing new hardware (like a nuc for esxi).  This laptop will be single purpose HA.

**Comment by CCOSTAN** [comment]
Leverage the wisdom here : https://github.com/Norien/Home-Assistant-Config/issues/143

cc:@norien

**Comment by bastshoes** [comment]
In this case I would go with dockers. Easy to install, lot easier to back up and you keep full control over system.

**Comment by CCOSTAN** [comment]
I'm going to give Dockers a shot.. I'll be new to it so expect a lot of bugs and questions. :) 

@bastshoes // @lapatoc

**Comment by bastshoes** [comment]
You are more than welcome!
@bastshoes=@lapatoc 😉

**Comment by onerealfunnyguy** [comment]
https://github.com/onerealfunnyguy/HA-Build  love having HA in docker!

**Comment by bastshoes** [comment]
Good example of dockeraised environment in https://github.com/onerealfunnyguy/HA-Build/tree/master/hive

**Comment by kylegordon** [comment]
I can highly recommend docker-compose as an orchestration tool, even if you just use it for one docker.

Grab the Linux binary from https://docs.docker.com/compose/install/#install-compose

This is my docker-compose.yaml, if it helps. Configs are stored on the local system in /docker/home-assistant/config, and it shares the USB port that my RFXCom generates when it's plugged in. Just docker-compose up -d to start (omit the -d to stay attached and watch the logs), and use 'docker pull  homeassistant/home-assistant' to get the latest copy when you need to update.

```
version: '3'

services:
  home-assistant:
    image: homeassistant/home-assistant:latest
    container_name: home-assistant
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=200
      - PGID=200
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 8123:8123
    volumes:
      - /docker/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro

    #logging:
    #  driver: syslog
    #  options:
    #    syslog-address: "udp://172.24.32.13:514"
```
