### ISSUE TITLE
Play around with ESPHOMEYaml for my NoceMCUs

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#379]
First Step down.. 

![image](https://user-images.githubusercontent.com/2160436/41385688-3398cdda-6f4b-11e8-8a96-6ecc7bf949da.png)

Docker image deployed. 
```
  esphomeyaml: 
    image: ottowinter/esphomeyaml:latest
    container_name: esphomeyaml
    command: esphomeyaml dashboard
    restart: always
    network_mode: "host"  
    ports:
      - 6052:6052
      - 6123:6123
    volumes:
      - /home/$USER/docker_files/esphomeyaml:/config
    environment:
      - TZ=America/New_York
```
