### ISSUE TITLE
Set up Alexa Media Players. 

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#421]
https://github.com/keatontaylor/custom_components/blob/master/media_player/alexa.py

https://paste.ubuntu.com/p/Sq7rv3mcPJ/

https://github.com/rrubin0/homeassistant-config/blob/master/packages/alexa_tts.yaml

cc: twooter, @keatontaylor, @rrubin0

**Comment by CCOSTAN** [comment]
100% I want to use the announcement features.. 

https://github.com/keatontaylor/alexa_media_player/wiki/Notification-Component
```yaml
- alias: Notification Test Weekly TTS
  initial_state: 'on'
  trigger:
    platform: time
    at: '12:15:00'
  condition:
    condition: time
    weekday:
      - wed
  action:
    - service: notify.alexa_media
      data:
        target: 
          - media_player.computer_room_dot
          - media_player.kitchen_dot
        #title: "My title for Echo show"
        data:
          type: announce
          #method: all
        message: "This is a weekly test of the announcing system."
```
