### ISSUE TITLE
Breaking Change : Move api_password to Home Assistant Auth

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#523]
```yaml
homeassistant:
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
      trusted_networks:
        - 192.168.10.0/24
```
