### ISSUE TITLE
Add WATER Delivery Reminder

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#541]
Add Boolean for WATER DELIVERY TO REMIND KIDS TO PUT OUT WATER BOTTLES THE NIGHT BEFORE WITH cHORE SPEECH.

**Comment by CCOSTAN** [comment]
I think this can be done pretty easy with some helpers and a card.  
```
trigger:
  - platform: time
    at: input_datetime.my_reminder
action:
  - service: notify.my_phone
    message: "{{ states('input_text.my_reminder') }}"
```
