### ISSUE TITLE
Power Outage Precautions

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#547]
When Power event is detected, turn Upstairs AC off.
When power is back, Restore to Cool.

Add in conditions that check for power outage on certain automations to minimize power usage.

**Comment by CCOSTAN** [comment]
Related: https://github.com/scottsweb/ham/issues/42

**Comment by CCOSTAN** [comment]
Can use this test condition for a lot of automations.
```yaml
  condition:
    - condition: template
      value_template: "{{ states('sensor.grid_status') == 'True' }}"
```
