### ISSUE TITLE
Update the Updater sensor

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#606]
Updater - The updater component is now a binary sensor that is always available. The entity ID is binary_sensor.updater. The state is on/off depending on whether an update is available or not. The latest version as well as the release notes are attributes of this binary sensor. Automations that are listening for the existence of updater.updater should now trigger when binary_sensor.updater changes to on. This makes the component more transparent and understandable for the user. Additionally, it is visible if there is an error or the source (https://updater.home-assistant.io/) is outdated. - (@Santobert - #25418) (updater docs)

**Comment by CCOSTAN** [comment]
https://github.com/thejeffreystone/home-assistant-configuration/issues/61#issuecomment-616659811

**Comment by CCOSTAN** [comment]
Let's implement this from @kylegordon ! 
https://github.com/kylegordon/home-assistant-config/blob/master/packages/update_notifier.yaml

**Comment by CCOSTAN** [comment]
```yaml
rest_command:
  new_version_github_issue:
    url: https://api.github.com/repos/kylegordon/home-assistant-config/issues
    method: POST
    headers:
      Authorization: !secret github_token
    payload: '{"title":"Home-Assistant {{ version }} available","body":"Home-Assistant {{ version }} is now available"}'

automation:
  alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.email_kyle
      data:
        title: "Home Assistant {{ states.updater.updater.state }} now available"
        message: "Update for Home Assistant is available. Version {{ states.updater.updater.state }} is out now!\nRelease notes: {{ states.updater.updater.attributes.release_notes }}"
    - service: rest_command.new_version_github_issue
      data_template:
        version: "{{ states.updater.updater.state }}"
```
