### ISSUE TITLE
Replace Fan in Bedroom

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#640]
The Fan Broke.  Needs replacing.  Now I need to decide how to smarten up it's replacement.

Should I just go regular Fan/Light with smart switches?  or Smart Fan like #98?

**Comment by CCOSTAN** [comment]
I do have some Noon ON/OFF Switches that I can use for Fan control (no dimming capabilities)..  Might be a good use for it. 

Also useful for the Closet light if I don't use the SemiSmart light fixture.  I don't know where else I would use them though. Maybe upstairs..

**Comment by jmart518** [comment]
I'm using GE z-wave fan switches for all my fans, they work very well

**Comment by CCOSTAN** [comment]
> I'm using GE z-wave fan switches for all my fans, they work very well

Thanks @jmart518 , I've been trying to get rid of the ZWave stuff so I can phase out my Wink Hub.  But I may have to revisit the Zwave stuff.  Really wanted to find a WiFi Fan or Fan switch.

**Comment by jmart518** [comment]
Oh yeah definitely understand that! What about an Aeotec Z-stick?

**Comment by CCOSTAN** [comment]
I used to run one of them with my Pi but when I switched over to Docker, I ditched it. #340 
But I technically still have it but I'm not sure how to go about linking it into a docker container/image.   I do have fans throughout the house so I guess once I have my Bedroom Fan worked out, I'll go ahead and replace them all to get control.   A generic fan with switch controller would be a LOT cheaper than a #98 BigAssFan though.. so it probably makes the most sense to go this route.  Wonder if there are any good Wifi Based Fan Controllers (Tuya?)

**Comment by brent20** [comment]
For me when I moved in to my new house, I added 433mhz canopy controllers to the fan in my bedroom and office (there was only a single switch for both the light and fan, so the GE Z-Wave switch was out) the canopy controllers allow for separate RF control of both the light and fan, but I put hue bulbs in the fan and leave them always on, and use a Broadlink RM Pro to send the RF commands to turn on/off the fans and control the speeds, this works great and highly recommend this route. The canopy controllers can be found at most hardware stores for $20-$30.

**Comment by ZetaPhoenix** [comment]
@CCOSTAN 

To get the zwave stick working with Docker:

```
$ cat 95-usb-serial.rules 
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="0001", SYMLINK+="ttyZWave"
```
Note, this is for a Gen 3 stick but the concept is the same. Source: http://hintshop.ludvig.co.nz/show/persistent-names-usb-serial-devices/

Then pass the persistant name to HA:
```yaml
  devices:
    - /dev/ttyZWave:/dev/ttyZWave
```

HA config:
```yaml
#Enable Z-Wave:
zwave:
  usb_path: /dev/ttyZWave
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_key
  autoheal: false
```

The other option for the fans are running tasmota on Sonoff iFan02 (replacement may be iFan03) https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-iFan02

Fan package:
```yaml
#https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant#ifan02-1

homeassistant:
group:
  guest_bedroom_ceiling_fan_group:
    view: no
    icon: mdi:fan
    name: Guest Bedroom Ceiling Fan
    entities:
      - fan.guest_bedroom_ceiling_fan
      - light.guest_bedroom_ceiling_light

fan:
  - platform: mqtt
    name: "Guest Bedroom Ceiling Fan"
    command_topic: "cmnd/br2-fan/FanSpeed"
    speed_command_topic: "cmnd/br2-fan/FanSpeed"
    state_topic: "stat/br2-fan/RESULT"
    speed_state_topic: "stat/br2-fan/RESULT"
    #state_value_template: "{% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
      {% else %}
        {% if states.fan.guest_bedroom_fan.state == 'off' -%}0{%- elif states.fan.guest_bedroom_fan.state == 'on' -%}4{%- endif %}
      {% endif %}
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: tele/br2-fan/LWT
    payload_off: "0"
    payload_on: "4"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    payload_available: Online
    payload_not_available: Offline
    qos: 1
    retain: false
    speeds:
      - 'off'
      - low
      - medium
      - high

light:
  - platform: mqtt
    name: "Guest Bedroom Ceiling Light"
    availability_topic: "tele/br2-fan/LWT"
    command_topic: "cmnd/br2-fan/POWER1"
    state_topic: "stat/br2-fan/POWER1"
    payload_available: Online
    payload_not_available: Offline
    payload_off: "OFF"
    payload_on: "ON"
    qos: 1
    retain: false
    optimistic: false
```
