### ISSUE TITLE
Convert Garadget to MQTT Fully.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#642]
The Cloud Service has REALLY started to act up so converting package to FULL MQTT. 

https://github.com/zybron/HomeAssistantConfig/blob/5fac2887a5115a12a81bb3a5ff66ae73cbbe8ac7/packages/garage.yaml

**Comment by CCOSTAN** [comment]
https://community.garadget.com/t/mqtt-support/3226/65

**Comment by codycodes** [comment]
Since that thread has a lot of different info, I wanted to post what's working for me in home assistant. You can change the name of "Garage" to whichever name you'd like. Also I had several issues when I flashed the device and it turns out that taking it out of my garage and going through the process of resetting it inside my home worked better for some reason. I don't remember what I did differently (maybe connecting to it with a different computer?) to make it work.

I'm using Mosquitto MQTT broker. I think most of the settings I have are the defaults. There was a point in the forum about not using a password that is over 30? chars I think. 

I'm using the following for my `configuration.yaml`:

```
cover:
  - platform: mqtt
    name: "Garage Door"
    command_topic: "garadget/Garage/command"
    state_topic: "garadget/Garage/status"
    value_template: >-
      {% if value_json.status == 'closed' %}
        closed
      {% else %}
        open
      {% endif %}
    device_class: 'garage'
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
```

And this in `automations.yaml` to poll for the status every minute:
```
- alias: '[Garage] Get Status'
  description: Query Garadget Status every minute
  trigger:
  - platform: time_pattern
    minutes: /1
  action:
    data:
      payload: get-status
      topic: garadget/Garage/command
    service: mqtt.publish
```

I have also configured a Ping component to keep in contact with Garadget
```
  - platform: ping
    host: !secret garadget_ip
    name: Garage Door Cover Ping
    scan_interval: 180
```

This allows me to see the status of the garage as a separate entity which I'm still hoping to integrate into a single one at this point. My goal is if the Garadget doesn't connect then its status goes to unavailable. But with the template above I just see the same status not changing if Garadget does go down, so I currently have my UI setup like this:

![image](https://user-images.githubusercontent.com/8005593/84054949-ff1cec80-a968-11ea-8e13-751370ff8d36.png)
