### ISSUE TITLE
CuckooClock stop working

### ISSUE THREAD

**Issue by ranrinc** [CCOSTAN/Home-AssistantConfig#724]
I use the script to run the cuckoo clock until recently suddenly it wont turn on anymore. Unsure what happen. Maybe someone can help?

```yaml
# Cuckoo Clock
alias: Cuckoo Clock
trigger:
  - platform: time_pattern
    hours: '*'
    minutes: '0'
  - platform: time_pattern
    minutes: '30'

condition:
  - condition: time
    after: '09:29:00'
    before: '21:01:00'
  - condition: template
    value_template: >
      {% if is_state('media_player.my_room_assistant', 'playing') %}
        false
      {% else %}
        true
      {% endif %}
  - condition: template
    value_template: >
      {% if is_state('media_player.family_room_assistant', 'playing') %}
        false
      {% else %}
        true
      {% endif %}
  - condition: template
    value_template: >
      {% if is_state('media_player.dining_room_assistant', 'playing') %}
        false
      {% else %}
        true
      {% endif %}

action:
  - service: media_player.play_media
    data_template:
      entity_id:
        - media_player.my_room_assistant
        - media_player.family_room_assistant
        - media_player.dining_room_assistant
      media_content_id: >
        {% if now().strftime("%M")|int == 30 %}
        /local/sounds/cuckoo-clock-01.wav
        {% else %}
        /local/sounds/cuckoo-clock-{{now().strftime("%I")}}.wav
        {% endif %}
      media_content_type: audio/mp4
```
wondering what happen
