### ISSUE TITLE
Lines of Code Sensor

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#729]
Add Lines of Code sensor for Twitter Purposes. 

```yaml 
- platform: command_line
name: config yaml lines
command: 'cat /root/config/configuration.yaml | wc -l'
```
![image](https://user-images.githubusercontent.com/2160436/79777986-0a0eb580-8306-11ea-8313-4ef9d82f1372.png)
