### ISSUE TITLE
Replaceable IOS notifications

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#750]
Add in the ability to replace notifications.  

https://companion.home-assistant.io/docs/notifications/notifications-basic#replacing-notifications

Specifically for my Medicine alert.

**Comment by CCOSTAN** [comment]
anyone have this working?

**Comment by jcallaghan** [comment]
Yes, let me post up my example tomorrow. I've been using it with my BBQ to keep replacing the internal temperature of the food I'm cooking with my Meater+ jcallaghan/home-assistant-config#50.

**Comment by CCOSTAN** [comment]
> Yes, let me post up my example tomorrow. I've been using it with my BBQ to keep replacing the internal temperature of the food I'm cooking with my Meater+ [jcallaghan/home-assistant-config#50](https://github.com/jcallaghan/home-assistant-config/issues/50).

Do the iOS notifications replace each other when a new one comes in?

**Comment by CCOSTAN** [comment]
Running this easy test shows that it is not working. :(  They keep creating new popups on the phone. 
![image](https://user-images.githubusercontent.com/2160436/83692197-852fe080-a5c1-11ea-95b4-3cac9072bbe3.png)
CAn someone else test this?
```yaml
title: "Test"
message: "This is a Test Message that should only appear once since it replaces the last one."
data:
  apns_headers:
    'apns-collapse-id': "Test_Message"
```

**Comment by pinkywafer** [comment]
Haven't got iPhones to test, and shouldn't make a difference, but the docs show the apns-collapse-id in single quotes, ie:
'apns-collapse-id': 'test_message'

**Comment by pinkywafer** [comment]
I've also seen many issues around the apns-collapse-id in many different projects, so could be any number of causes! I'd be inclined to try lower case only and no special characters also, in case certain characters are not supported.

**Comment by CCOSTAN** [comment]
Good Suggestions @pinkywafer .  I tried them but still no dice. 
```yaml
title: "Test"
message: "This is 1 Test Message that should only appear once since it replaces the last one."
data:
  apns_headers:
    'apns-collapse-id': 'test'
```
![image](https://user-images.githubusercontent.com/2160436/83697807-ea89ce80-a5cd-11ea-9464-3c16479e2e3e.png)
