### ISSUE TITLE
error in automation

### ISSUE THREAD

**Issue by pinkywafer** [CCOSTAN/Home-AssistantConfig#816]
Travis build is failing due to https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/automation/Speech/announcements.yaml :

```yaml
- alias: 'People Greeting'
  id: 29c5c9dd-550a-4761-a224-78cdc3dd9f43
  mode: restart
  trigger:
    - platform: state
      entity_id:
        - device_tracker.carlo
        - device_tracker.stacey
      from: 'not_home'
      to: 'home'
```
`mode` is not a valid key - not sure what you were trying to do here so haven't touched it!
