### ISSUE TITLE
Update Unifi Controller software to 6.x

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#900]
Need to wait til Friday in case there are issues.

**Comment by CCOSTAN** [comment]
Moved the Docker-Compose file to 
```
 unifi:
    image: jacobalberty/unifi:latest
    #image: jacobalberty/unifi:stable-5
    container_name: "Unifi"
    restart: always
    volumes:
      - ./unifi/data:/unifi/data
    network_mode: host
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 6789:6789/tcp
      - 8080:8080/tcp
      - 8880:8880/tcp
      - 8443:8443/tcp
      - 8843:8843/tcp
    environment:
      - TZ=America/New_York
      ```
