### ISSUE TITLE
Custom Commands via Alexa

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#944]
Umm.. The sky is the limit here I believe. 

This should give FULL control over any Alexa Device via HA. 

Use media_player.play_media
```yaml
entity_id: media_player.kitchen
media_content_id: 'what time is it'
media_content_type: custom
```
