### ISSUE TITLE
Change Echo Show to show BIG FONT CLOCK

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#954]
See if this can be done programmatically with Alexa Media Player component.

**Comment by CCOSTAN** [comment]
Changed it manually but looks like you can put pictures on there.  Might be useful in the future to put snapshots of security cameras on there at certain times.  Problem is there is not programmatic rollback at the moment. 

https://github.com/custom-components/alexa_media_player/wiki#set-echo-show-background

```yaml
entity_id: media_player.echo_show
media_content_id: "https://home-assistant.io/images/cast/splash.png"
media_content_type: image
```
