### ISSUE TITLE
Big Ass Fan

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#98]
For the living room. I want it.

**Comment by CCOSTAN** [comment]
http://amzn.to/2mfs8BK

**Comment by CCOSTAN** [comment]
Add spinning fan automation in Floorplan.

```css
@-webkit-keyframes rotation {
		from {
				-webkit-transform: rotate(0deg);
		}
		to {
				-webkit-transform: rotate(359deg);
		}
}

#fan\.living_room_fan_level, #fan\.master_bedroom_fan_level {
  transform-origin: center;
}

.fan-on {
  fill: #ff8a65 !important;
  -webkit-animation: rotation 2s infinite linear;
}

.fan-off {
  fill: #424242 !important;
}
```
